const CartTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS_TO_CART: "ADD_ITEMS_TO_CART",
  DELETE_ITEMS_FROM_CART: "DELETE_ITEMS_FROM_CART",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  CLEAR_CART: "CLEAR_CART",
};

export default CartTypes;
